name: Deploy to ECS with IAM Role

on:
 push:
   branches: [ main ]
 # workflow_dispatch:

 
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
   
    - name: Checkout
      uses: actions/checkout@master
          
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::255945442255:role/github-oidc-deploy-role
        aws-region: ap-southeast-1

   
    - name: Deploy with Terraform
      run: |
        terraform init
        terraform plan
        terraform apply -auto-approve