name: Deploy to ECS with IAM Role

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::AKIATXF4JQPH52H6D4ZJ:role/<CI/CD-OIDC-Role>
          aws-region: as-southeast-1

      - name: Deploy with Terraform
        run: |
          terraform init
          terraform apply -auto-approve