name: Deploy to ECS with IAM Role

on:
 push:
   branches: [ main ]
 # workflow_dispatch:

env:            
  AWS_REGION: ap-southeast-1 

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::255945442255:role/github-oidc-deploy-role
          role-session-name: GitHubActions
          aws-region: ${{ env.AWS_REGION }}
      - run: aws sts get-caller-identity

      - name: Deploy with Terraform
        run: |
          terraform init
          terraform apply -auto-approve