name: Deploy to ECS with IAM Role

on:
 push:
   branches: [ main ]
 # workflow_dispatch:

env:            
  AWS_REGION: ap-southeast-1 

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
          
      - name: Get OIDC token
        run: |
          echo "OIDC token:"
          curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" $ACTIONS_ID_TOKEN_REQUEST_URL

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::255945442255:role/github-oidc-deploy-role
          aws-region: ${{ env.AWS_REGION }}

   
      - name: Deploy with Terraform
        run: |
          terraform init
          terraform apply -auto-approve