name: Migrate Image from GHCR to ECR

on:
  workflow_dispatch:  # Manual trigger; change to 'push' if needed

jobs:
  ghcr-to-ecr:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      packages: read  # Required to access GHCR

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials (OIDC or secrets)
        uses: aws-actions/configure-aws-credentials@v4
        with:
         #OIDC (preferred)
        #role-to-assume: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<GITHUB_OIDC_ROLE>
        aws-region: ap-southeast-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull image from GHCR
        run: |
          docker pull ghcr.io/jpsankari/my-app:latest

      - name: Tag image for ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO: <your-ecr-repo>
          IMAGE_TAG: <tag>
        run: |
          docker tag ghcr.io/jpsankari/<image-name>:$IMAGE_TAG \
            $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG

      - name: Push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO: <your-ecr-repo>
          IMAGE_TAG: <tag>
        run: |
          docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG