name: Push GHCR image to ECR

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1  

      - name: Pull image from GHCR
        run: docker pull ghcr.io/jpsankari/my-app:latest

      - name: Tag image for ECR
        run: docker tag ghcr.io/jpsankari/my-app:latest 255945442255.dkr.ecr.ap-southeast-1.amazonaws.com/project17_myapp1-ecr:latest

      - name: Push image to ECR
        run: docker push 255945442255.dkr.ecr.ap-southeast-1.amazonaws.com/project17_myapp1-ecr:latest
