name: Build and Push image Docker to ECR

on:
  push:
    branches: [ "main" ]

env:            
  AWS_REGION: ap-southeast-1  
  IMAGE_TAG: latest
  ECR_REPOSITORY: ${{ secrets.REPOSITORY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build, tag, and push image to DockerHub
      env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_NAME: my-image
      run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME .
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

    - name: push Docker image to ECR        
      run: |
          IMAGE_URI=$ECR_REPOSITORY:$IMAGE_TAG
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI


  #test:
   # runs-on: ubuntu-latest
    #steps:
     # - name: Checkout code
      #  uses: actions/checkout@v2
      #- name: Set up Python
       # uses: actions/setup-python@v1
        #with:
         # python-version: '3.x'
      #- name: Install dependencies
       # run: |
        #  python -m pip install --upgrade pip
         # pip install -r requirements.txt
      #- name: Test with pytest
       # run: |
        #  pip install pytest
         # pytest test.py